//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public string id { get; set; }
        public string to_id { get; set; }
        public string from_id { get; set; }
        public string content_id { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
    
        public virtual Content_ Content_ { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
